name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install PostgreSQL
        run: sudo apt-get install -y postgresql postgresql-contrib

      - name: Start PostgreSQL service
        run: |
          sudo service postgresql start
          sudo -u postgres psql -q -c "SHOW server_version;"

      - name: Set up PostgreSQL DB
        run: |
          sudo -u postgres psql -q -c "CREATE DATABASE mydatabase;"

      - name: Build Backend
        working-directory: ./backend 
        run: mvn install

      - name: Generate Maven Site Report
        working-directory: ./backend  
        run: mvn clean site

      - name: Run Backend Tests
        working-directory: ./backend  
        env:
          DATABASE_URL: "jdbc:postgresql://localhost:5432/mydatabase"
          DATABASE_USER: "postgres"
          DATABASE_PASSWORD: "E@91e2l52"
        run: mvn test

      - name: Generate Surefire Report
        working-directory: ./backend 
        run: mvn surefire-report:report-only

      - name: Upload Maven Site Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: maven-site
          path: backend/target/site/  

      - name: Upload Surefire Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-report
          path: backend/target/site/surefire-report.html

      

  frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        working-directory: ./frontend  
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend 
        run: npm run build

      - name: Run Bundle Analysis
        working-directory: ./frontend  
        run: npm run analyze

      - name: Upload Bundle Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: bundle-report
          path: frontend/bundle-report.html
          if-no-files-found: warn

      - name: Run Frontend Tests
        working-directory: ./frontend  # Adjust this to the correct path
        run: npm test
