name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install PostgreSQL
        run: sudo apt-get install -y postgresql postgresql-contrib

      - name: Start PostgreSQL service
        run: |
          sudo service postgresql start
          sudo -u postgres psql -q -c "SHOW server_version;"

      - name: Set up PostgreSQL DB
        run: |
          sudo -u postgres psql -q -c "CREATE DATABASE mydatabase;"
          # Skip creating the postgres user as it already exists

      - name: Build Backend
        working-directory: ./backend 
        run: mvn install

      - name: Run Backend Tests
        working-directory: ./backend  
        env:
          DATABASE_URL: "jdbc:postgresql://localhost:5432/mydatabase"
          DATABASE_USER: "postgres"
          DATABASE_PASSWORD: "E@91e2l52"
        run: mvn test

      - name: Generate Backend Reports
        working-directory: ./backend  
        run: mvn surefire-report:report-only

      - name: Upload Surefire Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-report
          path: backend/target/site/surefire-report.html  # Path to the report

  frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build -- --stats-json

      - name: Run Frontend Tests
        run: npm test

      - name: Generate Coverage Report
        run: npm test -- --coverage
