name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up PostgreSQL
        run: sudo apt-get install -y postgresql postgresql-contrib

      - name: Start PostgreSQL service
        run: sudo service postgresql start

      - name: Set up PostgreSQL DB and user
        run: |
          sudo -u postgres psql -c "CREATE DATABASE mydatabase;"
          sudo -u postgres psql -c "CREATE USER myuser WITH ENCRYPTED PASSWORD 'mypassword';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE mydatabase TO myuser;"

      - name: Build Backend
        run: mvn install

      - name: Run Backend Tests
        run: mvn test

      - name: Generate Backend Reports
        run: mvn surefire-report:report

  frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.4'

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build -- --stats-json

      - name: Run Frontend Tests
        run: npm test

      - name: Generate Coverage Report
        run: npm test -- --coverage
